### ISSUE TITLE
MacVim Change the red forward slash after directory name in NerdTree

### ISSUE THREAD

**Issue by b-goldney** [sonph/onehalf#103]
Thanks for the awesome theme. How can we change the forward slash to be a color that isn't red?

**Comment by sonph** [comment]
Thanks, glad you like it!

I may be wrong, but I think NerdTree has a default set of color definitions that are not controlled by the onehalf themes. However if you just want to change the forward slash color, you can put this in the config file:

```
hi NERDTreeDirSlash guifg=5c6370 ctermfg=241
```

This will update the foreground color to match the comments. Change the color as you like :) For reference here's the list of color definitions: [link](https://github.com/sonph/onehalf/blob/89923117bc49dd1e0c6b7fdd34bc6dc4d425fe1f/vim/colors/onehalfdark.vim#L32).

Bonus: If you want to change other colors within NerdTree, type `:hi` in vim and you'll see a list of highlight groups. Scroll down the list to find `NERDTree...`.

![Screen Shot 2021-01-14 at 10 42 40 PM](https://user-images.githubusercontent.com/2466660/104690841-01db7f00-56ba-11eb-815c-f3b96309dbec.png)

**Comment by b-goldney** [comment]
Thank you - that worked. 

One minor clarification for anyone else interested:
The following line worked for me (notice the "#" after guifg). Also, this has to come after the OneHalf theme loads. The colors I input match the background of OneHalf so the forward slash disappears.

`hi NERDTreeDirSlash guifg=#282c34 ctermfg=236`
