### ISSUE TITLE
theme inconsistency whith coc

### ISSUE THREAD

**Issue by fabianoSL1** [sonph/onehalf#111]
The suggestion box show in a light theme.

![Captura de Tela (4)](https://user-images.githubusercontent.com/39917621/115718964-061ad680-a352-11eb-9565-eb71334eec8b.png)

**Comment by ashish10alex** [comment]
You can try changing  `~/.vim/plugged/onehalf/vim/colors/onehalfdark.vim` based on this pull request - ~/.vim/plugged/onehalf/vim/colors/onehalfdark.vim
