### ISSUE TITLE
Comments show with a grey bar 

### ISSUE THREAD

**Issue by ashish10alex** [sonph/onehalf#112]
<img width="1277" alt="Screenshot 2021-06-24 at 01 23 27" src="https://user-images.githubusercontent.com/34306898/123184052-c7f17e80-d48a-11eb-8393-a014f78f28a5.png">
I happen to get this grey bar on my comments when using the plugin on a macbook. It seems to work fine on ubuntu. 
Can you please guide me on how to resolve this ?

**Comment by GDLMendonca** [comment]
I'm getting the same thing...

**Comment by ashish10alex** [comment]
> I'm getting the same thing...
> 
> Temporary fix, add to .vimrc:
> `highlight Comment gui=none cterm=none`

Thanks, I have switched to `https://github.com/rakr/vim-one` for MacOS and using `Onehalf`on ubuntu.

**Comment by ashish10alex** [comment]
> I'm getting the same thing...
> 
> Temporary fix, add to .vimrc:
> `highlight Comment gui=none cterm=none`

**Comment by PovelikinRostislav** [comment]
The same issue for me...
![image](https://user-images.githubusercontent.com/20692004/123918222-533baa00-d98c-11eb-87ce-b637405a3af2.png)
