### ISSUE TITLE
Create Lightline Theme

### ISSUE THREAD

**Issue by garand** [sonph/onehalf#14]
Would you consider creating a theme for [Lightline](https://github.com/itchyny/lightline.vim)?

**Comment by sonph** [comment]
Sure I'll give it a try!

**Comment by sonph** [comment]
Haven't had much time to tweak it over the past week, but you can give the dark theme a try.

    Plugin 'sonph-forks/lightline.vim'
    " ...
    let g:lightline = {
      \ 'colorscheme': 'onehalfdark'
      \ }

Here's what it should look like
![screen shot 2016-06-29 at 2 33 32 pm](https://cloud.githubusercontent.com/assets/2466660/16469552/87fb09c4-3e06-11e6-9f00-30bba1079fe7.png)

**Comment by garand** [comment]
Thanks! I'll check it out.

**Comment by francis36012** [comment]
Hi @sonph, do you plan on adding the lightline colorscheme above to the plugin?

**Comment by sonph** [comment]
Dark theme merged in #18.
