### ISSUE TITLE
Suggestion: Adapt color scheme to Visual Studio Code

### ISSUE THREAD

**Issue by bbf** [sonph/onehalf#16]
The open source Visual Studio Code seems like a nice free alternative do Sublime Text. It would be great if your color scheme could also be used in it.

**Comment by bbf** [comment]
I was able to convert the sublime theme partially to VS Code by using the instructions here:
http://stackoverflow.com/questions/30011737/how-to-add-theme-in-visual-studio-code

The major difference  that I found so far is that the background color isn't exactly the same since I used  the VS's dark theme as base during the generation, so it might require a few tweaks. There's a way to public the theme to Microsoft, but I'll deffer that to you since you own it.

Thanks

**Comment by sonph** [comment]
I don't personally use VSCode so feel free to give it a shot and create a pull request.

If you are willing to maintain it then you're more than welcome to create a repo under your account, publish the theme under your name and I'll add a link to it. Again I don't use it so it's better to be maintained by someone using it on a daily basis.

Feel free to ask if you have any questions :beers:!
