### ISSUE TITLE
Xcode

### ISSUE THREAD

**Issue by jb-san** [sonph/onehalf#22]

**Comment by sonph** [comment]
I'll take a look this weekend.

**Comment by jb-san** [comment]
awesome thank you! :)

**Comment by sonph** [comment]
So I quickly cobbled together a pair of light/dark theme and they look sorta like:

![screen shot 2017-02-05 at 1 03 25 am-min](https://cloud.githubusercontent.com/assets/2466660/22625030/ec8eb4b2-eb3f-11e6-8069-e892452eae12.png)
![screen shot 2017-02-05 at 1 03 35 am-min](https://cloud.githubusercontent.com/assets/2466660/22625031/eca091fa-eb3f-11e6-8c87-c69513bbd7d3.png)

To try them out do:
```
wget https://raw.githubusercontent.com/sonph/onehalf/xcode/xcode/OneHalfDark.dvtcolortheme
wget https://raw.githubusercontent.com/sonph/onehalf/xcode/xcode/OneHalfLight.dvtcolortheme
mkdir -p ~/Library/Developer/Xcode/UserData/FontAndColorThemes/
cp *.dvtcolortheme ~/Library/Developer/Xcode/UserData/FontAndColorThemes/
```
then restart/open Xcode, go to Preferences > Fonts & Color and select One Half Light or One Half Dark.

I don't use Xcode a lot so let me know if something isn't right (i.e. hard to read or barely visible at all) or inconsistent! :beers:

**Comment by jb-san** [comment]
Thanks looks great

**Comment by sonph** [comment]
I've merged these two themes into master. Closing!
