### ISSUE TITLE
Please add support for italic fonts in vim (terminal)

### ISSUE THREAD

**Issue by nerdpad** [sonph/onehalf#24]
It would be nice to have support for italic fonts (comments, keywords, etc). There are currently a few themes that support it.

**Comment by sonph** [comment]
I think italic fonts isn't a very commonly used features in the terminal, even if the emulators support it. That being said, I can still look into experimenting with this.

**Comment by sonph** [comment]
For now if you want to have italic features, see this [question](http://stackoverflow.com/questions/3494435/vimrc-make-comments-italic) on stackoverflow.

```
hi Comment cterm=italic gui=italic
hi Keyword cterm=italic gui=italic
hi Type cterm=italic gui=italic
```
etc.
