### ISSUE TITLE
Theme for tmux

### ISSUE THREAD

**Issue by MarkRabey-Work** [sonph/onehalf#25]
Would love to see a theme matching for tmux - there is one that's close, but doesn't quite do it for me. I'd be happy to take it on as well.

**Comment by sonph** [comment]
Hmm I don't quite get what you mean by a theme for tmux. Can you explain?
Yes you can set the colors in your `tmux.conf` but they are only along the line of "set status bar background to black, foreground to red." It's then up to the terminal emulator to pick the shades of black and red as configured and display those colors.

**Comment by MarkRabey-Work** [comment]
There are tmux themes available out there. Essentially they're plugins that override terminal emulator settings. Maybe not necessary.

**Comment by sonph** [comment]
Ok I see what you're saying. Basically we can set the colors using the xterm 256 color palette like [this](https://github.com/jimeh/tmux-themepack/blob/master/powerline/double/blue.tmuxtheme).

```
set -g status-left "#[fg=colour232,bg=colour24] ..."
```

If you think it will be useful to others then sure feel free to work on it, open a pull request and I'll merge it!

**Comment by MarkRabey-Work** [comment]
Cool, I'll get on it later this week.

**Comment by dagadbm** [comment]
will this ever be done? :(
