### ISSUE TITLE
Colors are too bright in iTerm 2

### ISSUE THREAD

**Issue by sebastianks** [sonph/onehalf#35]
Hello

I'm very interested in using your theme - the dark one - but when I install it in vim for iTerm2 the colors are way too bright. I've added a screenshot.

Is this just the way things are, or are there some configurations that I need?

<img width="1680" alt="screen shot 2018-06-19 at 08 18 21" src="https://user-images.githubusercontent.com/2152027/41579978-6073634a-7399-11e8-8114-3beeb8e1356e.png">

**Comment by sonph** [comment]
Hey @sebastianks sorry for the late reply. You probably have figured it out by now. That's just the way it looks -- I prefer some lighter colors (but not eye-blindingly white) for better contrast and readability compared to something like solarized.

You can always fork the repo and tone down the colors to your liking :)

In iTerm2 (or 3) you can also do `Preferences > Appearance > Dimming`. Hope that helps!
