### ISSUE TITLE
Respect 'background' in vim

### ISSUE THREAD

**Issue by SevereOverfl0w** [sonph/onehalf#36]
Instead of 2 color schemes, the vim integration should be one. The distinction between light and dark should be made via the `'background'` setting, which can be either light or dark.

This is particularly useful for plugins such as https://github.com/amdt/sunset

**Comment by sonph** [comment]
Hi @SevereOverfl0w, setting `background` only works if the color scheme uses the same foreground colors for both light and dark, i.e. solarized, which doesn't give the desired contrast for readability. Onehalf uses lighter foreground colors for dark theme and darker foreground colors for light theme.

You can think of this as white on black (dark) and black on white (light), versus gray on white or gray on black.

If you want to achieve similar functionality to the plugin, I think it's simply a matter of replacing `set background=(light|dark)` with `colorscheme (onehalflight|onehalfdark)`.

**Comment by BlueDrink9** [comment]
As a workaround, I wrote this to automatically switch the scheme when '&background' changes:

```vim
augroup myColourschemes
    autocmd!
augroup end

autocmd myColourschemes colorscheme * let colorSch =
            \ get(g:, 'colors_name', 'default')

Plug 'sonph/onehalf', {'rtp': 'vim/'}
function! s:onehalfSwapLightDark()
  if g:colorSch =~? "dark"
    colorscheme onehalflight
  else
    colorscheme onehalfdark
  endif
endfunction
function! s:setOnehalfColourSwapAutocmd()
  au myColourschemes OptionSet background if g:colorSch =~? "onehalf" | call <sid>onehalfSwapLightDark() | endif
endfunction
" When using onehalf, set up an autocmd to change colourscheme when
" 'background' option is set (e.g. with `yob`)
au myColourschemes ColorScheme onehalf* call <sid>setOnehalfColourSwapAutocmd() | au! myColourschemes ColorScheme onehalf*
```

**Comment by Slotos** [comment]
> Hi @SevereOverfl0w, setting `background` only works if the color scheme uses the same foreground colors for both light and dark

I apologize for necroposting, but that is simply not true. Could be that it was true at some point, but I couldn't find when that point was.

[To quote help pages for `background` option](https://neovim.io/doc/user/options.html#'background'):

> This option does NOT change the background color, it tells Nvim what
>	the "inherited" (terminal/GUI) background looks like.

Moreover:

> When a color scheme is loaded (the "g:colors_name" variable is set)
>	setting ['background'](https://neovim.io/doc/user/options.html#'background') will cause the color scheme to be reloaded.  If
>	the color scheme adjusts to the value of ['background'](https://neovim.io/doc/user/options.html#'background') this will work.

Basically, colorscheme needs to read `&background` and uses the corresponding palette to just work.
