### ISSUE TITLE
Font used

### ISSUE THREAD

**Issue by cata0309** [sonph/onehalf#38]
What is the font used in the presentation image ?
![main 1](https://user-images.githubusercontent.com/35623921/44589472-54eac980-a7c1-11e8-9fb9-f4d62fe293f1.png)

**Comment by sonph** [comment]
Not 100% sure, but I believe that was [Source Code Pro](https://github.com/adobe-fonts/source-code-pro/releases).

**Comment by cata0309** [comment]
Nop, is not

**Comment by alexeyten** [comment]
Looks like Meslo LG

**Comment by sonph** [comment]
@cata0309 apologies, I switch fonts quite often. It's Menlo on macOS. Meslo LG seems to be a modified version of Menlo.
