### ISSUE TITLE
Include default usage in bat

### ISSUE THREAD

**Issue by haykam821** [sonph/onehalf#39]
This theme is used by default in [bat](https://github.com/sharkdp/bat) as of sharkdp/bat@67ec5fe2b7156b7ee5358e7f6c4995451ef1bbff, and this should be reflected when [talking about all the editors this theme supports](https://github.com/sonph/onehalf#features).

**Comment by sonph** [comment]
Hey thanks! I added `bat` to the list in commit c02594a
