### ISSUE TITLE
Airline color: *_modified mode color is same as normal_modified color.

### ISSUE THREAD

**Issue by caoyi5225** [sonph/onehalf#73]
Airline color:
The Insert mode color is blue, but the Insert_modified color is green like nomal_modified color.
Same for other modes. Is it designed like this?
If it is a bug, I'd like to submit a PR to fix it :)
Insert mode:
![image](https://user-images.githubusercontent.com/21326015/77057681-47cea480-6a0f-11ea-97b5-3ec31b6c8035.png)
Insert_modified mode:
![image](https://user-images.githubusercontent.com/21326015/77057718-56b55700-6a0f-11ea-984f-b443ab1a7a16.png)
expect Insert_modefied mode:
![image](https://user-images.githubusercontent.com/21326015/77057861-90865d80-6a0f-11ea-99e6-47c57912d365.png)

**Comment by Alex-Muirhead** [comment]
@caoyi5225 Did you resolve this issue? If you did, could you please explain how?

**Comment by caoyi5225** [comment]
> @caoyi5225 Did you resolve this issue? If you did, could you please explain how?

Check this: https://github.com/caoyi5225/onehalf/commit/272c13c721fcbdf326c156d24193b9223a9a09e1

**Comment by caoyi5225** [comment]
@Alex-Muirhead 

Check this: https://github.com/caoyi5225/onehalf/commit/272c13c721fcbdf326c156d24193b9223a9a09e1

**Comment by Alex-Muirhead** [comment]
@caoyi5225 Thank you, this works wonderfully
