### ISSUE TITLE
VIM NonText Color should match be less visually intrusive

### ISSUE THREAD

**Issue by RussBrown00** [sonph/onehalf#96]
The current setting `call s:h("NonText", s:fg, "", "")` Should really be a darker color closer the the background color for improved readability/usability. Something even closer to the comment color would work, but I'm personally using: `hi NonText guifg=#474d59 ctermfg=237` and it's a massive improvement.

OLD:
![image](https://user-images.githubusercontent.com/4053376/95865048-32ff8880-0d34-11eb-956d-8ee2a6691432.png)

CHANGE SUGGESTION:
![image](https://user-images.githubusercontent.com/4053376/95865175-5e827300-0d34-11eb-9897-f75fd337ac73.png)

**Comment by sonph** [comment]
Yep totally agree with you. I haven't used vim in a while and don't enable :set list so I wasn't aware of that. If the comment fg color works, do you mind creating a pull request similar to #94?

**Comment by sonph** [comment]
Fixed in #97 🍻
